#!/usr/bin/env bun
/**
 * Regenerates packages/web/src/theme/presets.generated.css from
 * packages/web/src/theme/presets.ts.
 *
 * Why: a theme is generated from three inputs, but the five NAMED themes never
 * change at runtime. Compiling them to plain CSS means five of the six themes
 * cost nothing to apply, cannot flash before first paint, and do not ship the
 * oklch maths to the browser. Only a user's Custom theme is generated live.
 *
 * The generator is the single source for both paths, so a preset and a custom
 * theme built from the same triple are identical by construction rather than
 * by two implementations agreeing.
 *
 * Usage:
 *   bun run scripts/generate-theme-css.ts          # write
 *   bun run scripts/generate-theme-css.ts --check  # verify (exit 2 if stale)
 *
 * Exit codes:
 *   0  file generated (and unchanged, if --check)
 *   1  unexpected error
 *   2  --check was passed and the file would change
 */
import { readFile, writeFile } from 'fs/promises';
import { join, resolve } from 'path';
import { generateTheme, polarityOf, tokensToCss } from '../packages/web/src/theme/generate';
import { PRESETS } from '../packages/web/src/theme/presets';

const REPO_ROOT = resolve(import.meta.dir, '..');
const OUTPUT_PATH = join(REPO_ROOT, 'packages/web/src/theme/presets.generated.css');
const CHECK_ONLY = process.argv.includes('--check');

function build(): string {
  const blocks = PRESETS.map(preset => {
    const tokens = generateTheme(preset);
    const polarity = polarityOf(preset.background);
    return (
      `/* ${preset.label} — accent ${preset.accent}, background ${preset.background}, ` +
      `contrast ${String(preset.contrast)} */\n` +
      `[data-theme='${preset.id}'] .console-root {\n` +
      `  color-scheme: ${polarity};\n  ${tokensToCss(tokens)}\n}`
    );
  });
  return (
    '/* GENERATED by scripts/generate-theme-css.ts — do not edit.\n' +
    ' * Source: packages/web/src/theme/presets.ts\n' +
    ' * Run: bun run generate:theme-css\n */\n\n' +
    `${blocks.join('\n\n')}\n`
  );
}

async function main(): Promise<void> {
  const contents = build();
  if (CHECK_ONLY) {
    let existing: string | null = null;
    try {
      existing = (await readFile(OUTPUT_PATH, 'utf-8')).replace(/\r\n/g, '\n');
    } catch (e) {
      const err = e as NodeJS.ErrnoException;
      if (err.code !== 'ENOENT') throw err;
    }
    if (existing !== contents) {
      console.error(
        'presets.generated.css is stale vs presets.ts.\nRun: bun run generate:theme-css'
      );
      process.exit(2);
    }
    console.log('check:theme-css OK');
    return;
  }
  await writeFile(OUTPUT_PATH, contents, 'utf-8');
  console.log(`Generated ${OUTPUT_PATH} (${String(PRESETS.length)} presets)`);
}

main().catch(err => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
